name: Windows Self-Hosted Runner Test with Artifact

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      # Step 1: Create Report File
      - name: Create Report
        run: |
          echo Operating System: %OS% > report.txt
          echo Computer Name: %COMPUTERNAME% >> report.txt
          echo Running on a Windows self-hosted runner >> report.txt

      # Step 2: Test PowerShell Command (Using Windows PowerShell)
      - name: Test PowerShell Command
        shell: powershell
        run: |
          "Hello from PowerShell!" | Add-Content -Path report.txt
          Get-Date | Add-Content -Path report.txt

      # Step 3: Verify Environment Variables
      - name: Verify Environment
        run: |
          echo Current Directory: %cd% >> report.txt
          echo Logged-in User: %username% >> report.txt
          echo PATH Environment Variable: %PATH% >> report.txt

      # Step 4: Upload Report as Artifact
      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-runner-test-report
          path: report.txt
